// src/lib/types.ts

/**
 * Defines the structure for a study resource, which can be an internal markdown file
 * or an external URL.
 */
export type StudyResource = {
  title: string;
  category: string;
  type: 'internal' | 'url';
  source: string; // Path to markdown file or external URL
};

/**
 * Defines the structure for a single question in any quiz.
 */
export type GeneratedQuestion = {
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  topic: string;
};

/**
 * Defines the structure for a complete quiz, which can be a standard topic quiz,
 * a psychometric test, or a full exam simulation.
 */
export type GeneratedQuiz = {
  title: string;
  topic: string;
  questions: GeneratedQuestion[];
  isPsychometric?: boolean; // Flag for timed quizzes (psychometric or simulation)
  timeLimit?: number; // Time limit in minutes
};

/**
* Defines the structure for the user's performance data, tracking correct and
* incorrect answers per topic.
*/
export type PerformanceData = {
  topic: string;
  correct: number;
  incorrect: number;
};

/**
 * Defines the structure for a summary generated by the AI and saved by the user.
 */
export type SavedSummary = {
  id: string;
  title: string;
  content: string;
  originalUrl: string;
  createdAt: string;
};

/**
 * Defines the structure for the personalized feedback object generated by the AI
 * after a user answers a question in a quiz.
 */
export type Feedback = {
  feedback: string;
  areasForImprovement: string;
  adaptedQuestionTopic: string;
  timestamp: string;
  topic: string;
};

/**
 * Defines the structure for the learning style quiz questions.
 */
export type LearningStyleQuestion = {
  id: string;
  question: string;
  options: {
    style: 'V' | 'A' | 'R' | 'K';
    text: string;
  }[];
};

/**
 * Defines the structure for the saved learning strategy.
 */
export type LearningStrategy = {
  style: string;
  strategy: string;
};
