'use client';
import { useState } from 'react';
import type { GeneratedQuiz, GeneratedQuestion, Feedback } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Loader2, CheckCircle, XCircle, Lightbulb, ArrowLeft } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { analyzePerformanceAndAdapt } from '@/ai/flows/personalized-feedback-adaptation';
import { updatePerformanceData, saveFeedback } from '@/lib/services';

type GeneratedQuizProps = {
    quiz: GeneratedQuiz;
    onBack: () => void;
};

/**
 * Renders an interactive quiz generated by the AI.
 * It manages the quiz state, including the current question, user's score,
 * and feedback process after each answer.
 *
 * @param {GeneratedQuizProps} props - The quiz data and a callback function to return to the previous view.
 */
export function GeneratedQuiz({ quiz, onBack }: GeneratedQuizProps) {
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [isAnswered, setIsAnswered] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);
  const [score, setScore] = useState(0);
  const [feedback, setFeedback] = useState<Feedback | null>(null);
  const [isLoading, setIsLoading] = useState(false);


  const currentQuestion: GeneratedQuestion = quiz.questions[currentQuestionIndex];
  const isQuizFinished = currentQuestionIndex >= quiz.questions.length;

  /**
   * Handles the submission of an answer. It checks for correctness, updates the score,
   * stores performance data, and fetches personalized feedback from the AI.
   */
  const handleAnswerSubmit = async () => {
    if (!selectedAnswer) return;

    setIsLoading(true);
    setIsAnswered(true);
    const correct = selectedAnswer === currentQuestion.correctAnswer;
    setIsCorrect(correct);
    
    if (correct) {
      setScore(score + 1);
    }
    
    // Update performance data in localStorage for the specific topic.
    updatePerformanceData(quiz.topic, correct);

    try {
      // Get personalized feedback from the AI based on the user's answer.
      const result = await analyzePerformanceAndAdapt({
        question: currentQuestion.question,
        studentAnswer: selectedAnswer,
        correctAnswer: currentQuestion.correctAnswer,
        topic: quiz.topic,
      });
      const newFeedback: Feedback = {...result, timestamp: new Date().toISOString(), topic: quiz.topic};
      setFeedback(newFeedback);
      saveFeedback(newFeedback); // Save the feedback to localStorage.
    } catch (error) {
      console.error("Error getting feedback:", error);
      // Provide a fallback feedback message in case of an error.
      const errorFeedback: Feedback = {
        feedback: "No se pudo obtener la retroalimentación. Por favor, intenta de nuevo.",
        areasForImprovement: "N/A",
        adaptedQuestionTopic: quiz.topic,
        timestamp: new Date().toISOString(),
        topic: quiz.topic,
      }
      setFeedback(errorFeedback);
      saveFeedback(errorFeedback);
    } finally {
      setIsLoading(false);
    }
  };

  /**
   * Moves to the next question in the quiz, resetting the state for the new question.
   */
  const handleNextQuestion = () => {
    setCurrentQuestionIndex(currentQuestionIndex + 1);
    setSelectedAnswer(null);
    setIsAnswered(false);
    setFeedback(null);
  };

  /**
   * Resets the quiz to the beginning, clearing the score and all question states.
   */
  const handleRestartQuiz = () => {
    setCurrentQuestionIndex(0);
    setScore(0);
    setSelectedAnswer(null);
    setIsAnswered(false);
    setFeedback(null);
  }

  // Render the quiz completion summary if all questions have been answered.
  if (isQuizFinished) {
    return (
      <Card className="w-full max-w-2xl mt-4">
        <CardHeader>
          <CardTitle className="font-headline text-2xl">¡Quiz Completado!</CardTitle>
          <CardDescription>Resultado del quiz sobre: {quiz.title}</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center text-4xl font-bold">
            {score} / {quiz.questions.length}
          </div>
          <p className="text-center text-muted-foreground mt-2">
            Respuestas correctas
          </p>
           <p className="text-center text-sm text-muted-foreground mt-4">Puedes revisar tu retroalimentación detallada en la sección "Mi Progreso".</p>
        </CardContent>
        <CardFooter className="flex-col sm:flex-row gap-2">
           <Button onClick={onBack} className="w-full sm:w-auto" variant="outline">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Elegir otro Tema
          </Button>
          <Button onClick={handleRestartQuiz} className="w-full sm:w-auto">
            Volver a Intentar
          </Button>
        </CardFooter>
      </Card>
    );
  }

  // Render the current question.
  return (
    <Card className="w-full max-w-2xl mt-4">
      <CardHeader>
        <div className="flex justify-between items-center">
            <Button variant="ghost" size="sm" onClick={onBack} className="self-start">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Volver
            </Button>
            <CardTitle className="font-headline text-lg">{quiz.title}</CardTitle>
        </div>
        <CardDescription>Pregunta {currentQuestionIndex + 1} de {quiz.questions.length}</CardDescription>
        <Progress value={((currentQuestionIndex + 1) / quiz.questions.length) * 100} className="mt-2" />
        <p className="pt-4 text-lg">{currentQuestion.question}</p>
      </CardHeader>
      <CardContent>
        <RadioGroup
          value={selectedAnswer ?? ''}
          onValueChange={setSelectedAnswer}
          disabled={isAnswered}
        >
          {currentQuestion.options.map((option, index) => (
            <div key={index} className="flex items-center space-x-2 p-2 rounded-md transition-colors hover:bg-muted">
              <RadioGroupItem value={option} id={`option-gen-${index}`} />
              <Label htmlFor={`option-gen-${index}`} className="text-base cursor-pointer flex-1">{option}</Label>
            </div>
          ))}
        </RadioGroup>

        {/* Display feedback and explanation after an answer is submitted */}
        {isAnswered && (
          <div className="mt-6 space-y-4">
             <Alert variant={isCorrect ? 'default' : 'destructive'} className={isCorrect ? 'border-green-500 bg-green-50 dark:bg-green-900/20' : ''}>
              {isCorrect ? <CheckCircle className="h-4 w-4 text-green-500" /> : <XCircle className="h-4 w-4" />}
              <AlertTitle>{isCorrect ? '¡Correcto!' : 'Incorrecto'}</AlertTitle>
              <AlertDescription>
                {isCorrect ? '¡Buen trabajo!' : `La respuesta correcta es: ${currentQuestion.correctAnswer}`}
              </AlertDescription>
            </Alert>
            <Alert>
              <Lightbulb className="h-4 w-4" />
              <AlertTitle>Explicación</AlertTitle>
              <AlertDescription>
                {currentQuestion.explanation}
              </AlertDescription>
            </Alert>
            {isLoading && (
              <div className="flex items-center gap-2 text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" />
                Analizando tu respuesta y adaptando tu ruta...
              </div>
            )}
            {feedback && !isLoading && (
              <Alert className="border-primary">
                <Lightbulb className="h-4 w-4 text-primary" />
                <AlertTitle>Retroalimentación Personalizada</AlertTitle>
                <AlertDescription>
                  <p className="font-semibold mt-2">Sugerencia de la IA:</p>
                  <p>{feedback.feedback}</p>
                  <p className="mt-2 font-semibold">Área de mejora sugerida:</p>
                  <p>{feedback.areasForImprovement}</p>
                </AlertDescription>
              </Alert>
            )}
          </div>
        )}
      </CardContent>
      <CardFooter>
        {isAnswered ? (
          <Button onClick={handleNextQuestion} className="w-full">
            Siguiente Pregunta
          </Button>
        ) : (
          <Button onClick={handleAnswerSubmit} disabled={!selectedAnswer || isLoading} className="w-full">
            {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Enviar Respuesta
          </Button>
        )}
      </CardFooter>
    </Card>
  );
}
